## PC/errmap.h
import std/winlean
import ./errmap

const
  WSAEBADF = 10003
  WSAEACCES = 10013
  WSAEFAULT = 10014
  WSAEINVAL = 10022
  WSAEMFILE = 10024

  ERROR_INVALID_DRIVE = 15
  ERROR_BAD_NETPATH = 53
  ERROR_BAD_NET_NAME = 67
  ERROR_BAD_PATHNAME = 161
  ERROR_FILENAME_EXCED_RANGE = 206

  ERROR_BAD_ENVIRONMENT = 10

  ERROR_BAD_FORMAT = 11
  ERROR_INVALID_STARTING_CODESEG = 188
  ERROR_INVALID_STACKSEG = 189
  ERROR_INVALID_MODULETYPE = 190
  ERROR_INVALID_EXE_SIGNATURE = 191
  ERROR_EXE_MARKED_INVALID = 192

  ERROR_BAD_EXE_FORMAT = 193
  ERROR_ITERATED_DATA_EXCEEDS_64k = 194
  ERROR_INVALID_MINALLOCSIZE = 195
  ERROR_DYNLINK_FROM_INVALID_RING = 196
  ERROR_IOPL_NOT_ENABLED = 197
  ERROR_INVALID_SEGDPL = 198

  ERROR_AUTODATASEG_EXCEEDS_64k = 199
  ERROR_RING2SEG_MUST_BE_MOVABLE = 200
  
  
  ERROR_RELOC_CHAIN_XEEDS_SEGLIM = 201
  ERROR_INFLOOP_IN_RELOC_CHAIN = 202


  ERROR_INVALID_HANDLE = 6
  ERROR_INVALID_TARGET_HANDLE = 114
  ERROR_DIRECT_ACCESS_HANDLE = 130

  ERROR_WAIT_NO_CHILDREN = 128
  ERROR_CHILD_NOT_COMPLETE = 129
  

  ERROR_NO_PROC_SLOTS = 89
  ERROR_MAX_THRDS_REACHED = 164
  ERROR_NESTING_NOT_ALLOWED = 215

  ERROR_ARENA_TRASHED = 7
  ERROR_NOT_ENOUGH_MEMORY = 8
  ERROR_INVALID_BLOCK = 9
  ERROR_NOT_ENOUGH_QUOTA = 1816

  ERROR_CURRENT_DIRECTORY = 16
  ERROR_WRITE_PROTECT = 19
  ERROR_BAD_UNIT = 20
  ERROR_NOT_READY = 21
  ERROR_BAD_COMMAND = 22
  ERROR_CRC = 23

  ERROR_BAD_LENGTH = 24
  ERROR_SEEK = 25
  ERROR_NOT_DOS_DISK = 26
  ERROR_SECTOR_NOT_FOUND = 27
  ERROR_OUT_OF_PAPER = 28
  ERROR_WRITE_FAULT = 29
  ERROR_READ_FAULT = 30
  ERROR_GEN_FAILURE = 31

  ERROR_SHARING_VIOLATION = 32
  ERROR_LOCK_VIOLATION = 33
  ERROR_WRONG_DISK = 34
  ERROR_SHARING_BUFFER_EXCEEDED = 36
  ERROR_NETWORK_ACCESS_DENIED = 65

  ERROR_CANNOT_MAKE = 82
  ERROR_FAIL_I24 = 83
  
  ERROR_DRIVE_LOCKED = 108
  ERROR_SEEK_ON_DEVICE = 132
  ERROR_NOT_LOCKED = 158
  ERROR_LOCK_FAILED = 167


  ERROR_ALREADY_EXISTS = 183

  ERROR_NOT_SAME_DEVICE = 17

  ERROR_DIRECTORY = 267  # bpo-12802

  ERROR_TOO_MANY_OPEN_FILES = 4

  ERROR_DISK_FULL = 112

  ERROR_BROKEN_PIPE = 109
  ERROR_NO_DATA = 232  # bpo-13063

  ERROR_DIR_NOT_EMPTY = 145

  ERROR_NO_UNICODE_TRANSLATION = 1113

  ERROR_INVALID_FUNCTION = 1

  ERROR_INVALID_ACCESS = 12
  ERROR_INVALID_DATA = 13
  ERROR_INVALID_PARAMETER = 87
  ERROR_NEGATIVE_SEEK = 131


proc winerror_to_errno*(winerror: cint): cint =
  # Unwrap FACILITY_WIN32 HRESULT errors
  var winerror = winerror
  if (winerror and 0xFFFF0000) == 0x80070000:
    winerror = winerror and 0x0000FFFF

  # Winsock error codes (10000-11999) are errno values
  if winerror >= 10000 and winerror < 12000:
    case winerror
    of WSAEINTR, WSAEBADF, WSAEACCES, WSAEFAULT, WSAEINVAL, WSAEMFILE:
      # Winsock definitions of errno values. See WinSock2.h
      return winerror - 10000
    else:
      return winerror

  case winerror
  of ERROR_FILE_NOT_FOUND, ERROR_PATH_NOT_FOUND, ERROR_INVALID_DRIVE,
     ERROR_NO_MORE_FILES, ERROR_BAD_NETPATH, ERROR_BAD_NET_NAME,
     ERROR_BAD_PATHNAME, ERROR_FILENAME_EXCED_RANGE:
    ENOENT

  of ERROR_BAD_ENVIRONMENT:
    E2BIG

  of ERROR_BAD_FORMAT, ERROR_INVALID_STARTING_CODESEG, ERROR_INVALID_STACKSEG,
     ERROR_INVALID_MODULETYPE, ERROR_INVALID_EXE_SIGNATURE, ERROR_EXE_MARKED_INVALID,
     ERROR_BAD_EXE_FORMAT, ERROR_ITERATED_DATA_EXCEEDS_64k, ERROR_INVALID_MINALLOCSIZE,
     ERROR_DYNLINK_FROM_INVALID_RING, ERROR_IOPL_NOT_ENABLED, ERROR_INVALID_SEGDPL,
     ERROR_AUTODATASEG_EXCEEDS_64k, ERROR_RING2SEG_MUST_BE_MOVABLE,
     ERROR_RELOC_CHAIN_XEEDS_SEGLIM, ERROR_INFLOOP_IN_RELOC_CHAIN:
    ENOEXEC

  of ERROR_INVALID_HANDLE, ERROR_INVALID_TARGET_HANDLE, ERROR_DIRECT_ACCESS_HANDLE:
    EBADF

  of ERROR_WAIT_NO_CHILDREN, ERROR_CHILD_NOT_COMPLETE:
    ECHILD

  of ERROR_NO_PROC_SLOTS, ERROR_MAX_THRDS_REACHED, ERROR_NESTING_NOT_ALLOWED:
    EAGAIN

  of ERROR_ARENA_TRASHED, ERROR_NOT_ENOUGH_MEMORY, ERROR_INVALID_BLOCK,
     ERROR_NOT_ENOUGH_QUOTA:
    ENOMEM

  of ERROR_ACCESS_DENIED, ERROR_CURRENT_DIRECTORY, ERROR_WRITE_PROTECT,
     ERROR_BAD_UNIT, ERROR_NOT_READY, ERROR_BAD_COMMAND, ERROR_CRC,
     ERROR_BAD_LENGTH, ERROR_SEEK, ERROR_NOT_DOS_DISK, ERROR_SECTOR_NOT_FOUND,
     ERROR_OUT_OF_PAPER, ERROR_WRITE_FAULT, ERROR_READ_FAULT, ERROR_GEN_FAILURE,
     ERROR_SHARING_VIOLATION, ERROR_LOCK_VIOLATION, ERROR_WRONG_DISK,
     ERROR_SHARING_BUFFER_EXCEEDED, ERROR_NETWORK_ACCESS_DENIED, ERROR_CANNOT_MAKE,
     ERROR_FAIL_I24, ERROR_DRIVE_LOCKED, ERROR_SEEK_ON_DEVICE, ERROR_NOT_LOCKED,
     ERROR_LOCK_FAILED, 35:
    EACCES

  of ERROR_FILE_EXISTS, ERROR_ALREADY_EXISTS:
    EEXIST

  of ERROR_NOT_SAME_DEVICE:
    EXDEV

  of ERROR_DIRECTORY:
    ENOTDIR

  of ERROR_TOO_MANY_OPEN_FILES:
    EMFILE

  of ERROR_DISK_FULL:
    ENOSPC

  of ERROR_BROKEN_PIPE, ERROR_NO_DATA:
    EPIPE

  of ERROR_DIR_NOT_EMPTY:
    ENOTEMPTY

  of ERROR_NO_UNICODE_TRANSLATION:
    EILSEQ

  of WAIT_TIMEOUT:
    ETIMEDOUT

  of ERROR_INVALID_FUNCTION, ERROR_INVALID_ACCESS, ERROR_INVALID_DATA,
     ERROR_INVALID_PARAMETER, ERROR_NEGATIVE_SEEK:
    EINVAL

  else:
    EINVAL

when isMainModule:
  echo winerror_to_errno(ERROR_FILE_NOT_FOUND)
